### ISSUE TITLE
mapit_global_import 

### ISSUE THREAD

**Issue by fixmystreetfr** [mysociety/mapit#206] opened 2015-10-20 01:48 UTC
hello,
when i try to import with ./manage.py mapit_global_import --verbosity 2 --commit data/cache-with-political/
i've got this error behind, is there a solution to correct it easily ?

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATE                                           S dictionary takes precedence. You must put the values of the following settings into your defa                                           ult TEMPLATES dict: TEMPLATE_CONTEXT_PROCESSORS, TEMPLATE_LOADERS.
Loading any admin boundaries from data/cache-with-political/
Finding language codes...
Loading type O02
Loading all KML in O02
[0% complete] Loading /var/www/xxxxxxxxxx
Ecuador.kml
  Ecuador
    No area existed in the current generation with that OSM element type and ID
    Area ID: 1
[0% complete] Loading /var/www/mapit.fixmystreet.fr/mapit/data/cache-with-political/O02/relatio n-1152720-ÐÐ±Ñ
Ð°Ð•Ð¸Ñ - ÐÒ§ÑÐ½Ñ.kml

UnicodeEncodeError: 'ascii' codec can't encode characters in position 21-27: ordinal not in range(128)

**Comment by dracos** [comment] 2015-10-20 12:37
Sorry to hear you've had problems. Could you provide the entire traceback? It should include the line number that's going wrong. It looks like it's the print line of the country name, but I can't be sure without the full details.

One possibility, could you try downgrading Django to 1.7 and seeing if it runs okay then? I'm not sure what difference that would make, but it's possible that import script hasn't been tested under 1.8 and there is some subtle difference that needs looking at.

It should work okay, here's that area imported in our installation: http://global.mapit.mysociety.org/area/687137.html
We need to update our own installation, so I will set that running now and see if I come across any similar issues.

**Comment by fixmystreetfr** [comment] 2015-10-20 16:48
./manage.py mapit_global_import --verbosity 2 --commit data/cache-with-political/

System check identified some issues:

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATE                                           S dictionary takes precedence. You must put the values of the following settings into your defa                                           ult TEMPLATES dict: TEMPLATE_CONTEXT_PROCESSORS, TEMPLATE_LOADERS.
Loading any admin boundaries from data/cache-with-political/
Finding language codes...
Loading type O02
Loading all KML in O02
[0% complete] Loading /var/www/mapit.testserveur.fr/mapit/data/cache-with-political/O02/relatio                                           n-108089-Ecuador.kml
  Ecuador
    No area existed in the current generation with that OSM element type and ID
    Area ID: 1
.
[0% complete] Loading /var/www/mapit.testserveur.fr/mapit/data/cache-with-political/O02/relatio                                           n-1111111-Deutschland.kml
  Deutschland
    Invalid KML:O02/relation-1111111-Deutschland.kml
    No area existed in the current generation with that OSM element type and ID
    Area ID: 2
.
[0% complete] Loading /var/www/mapit.testserveur.fr/mapit/data/cache-with-political/O02/relatio                                           n-1124039-Monaco.kml
  Monaco
    No area existed in the current generation with that OSM element type and ID
    Area ID: 3
.
[0% complete] Loading /var/www/mapit.testserveur.fr/mapit/data/cache-with-political/O02/relatio                                           n-114686-Estados Unidos Mexicanos.kml
  Estados Unidos Mexicanos
    No area existed in the current generation with that OSM element type and ID
    Area ID: 4
.
[0% complete] Loading /var/www/mapit.testserveur.fr/mapit/data/cache-with-political/O02/relatio                                           n-1152720-ÐÐ±Ñ
Ð°Ð•Ð¸Ñ - ÐÒ§ÑÐ½Ñ.kml
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/mapit.testserveur.fr/virtualenv-mapit/local/lib/python2.7/site-packages/django                                           /core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/var/www/mapit.testserveur.fr/virtualenv-mapit/local/lib/python2.7/site-packages/django                                           /core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/mapit.testserveur.fr/virtualenv-mapit/local/lib/python2.7/site-packages/django                                           /core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/mapit.testserveur.fr/virtualenv-mapit/local/lib/python2.7/site-packages/django                                           /core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/var/www/mapit.testserveur.fr/virtualenv-mapit/local/lib/python2.7/site-packages/django                                           /core/management/base.py", line 623, in handle
    label_output = self.handle_label(label, **options)
  File "/var/www/mapit.testserveur.fr/mapit/mapit_global/management/commands/mapit_global_impor                                           t.py", line 166, in handle_label
    xml.sax.parse(kml_filename, kml_data)
  File "/usr/lib/python2.7/xml/sax/__init__.py", line 33, in parse
    parser.parse(source)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 119, in parse
    self.prepareParser(source)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 111, in prepareParser
    self._parser.SetBase(source.getSystemId())
UnicodeEncodeError: 'ascii' codec can't encode characters in position 21-27: ordinal not in range(128)

**Comment by dracos** [comment] 2015-10-20 17:08
Okay, so that error is being thrown by the XML reader (so I don't think you need to bother downgrading Django, I can't see that changing anything). The KML file that it is erroring on, relation 1152720, is that file valid XML? Is there anything about it you can see that looks wrong?
On my server, the file is listed as: ...`mapit/data/cache-with-political/O02/relation-1152720-Абхазия - Аҧсны.kml` so my guess is the issue lies with your server in some way. Is it running a Unicode locale?

**Comment by dracos** [comment] 2015-10-20 17:35
I have replicated the issue locally. It looks to be a bug in python 2.7.3, fixed in 2.7.4: https://bugs.python.org/issue11159
If you can't upgrade to a newer 2.7 python, we can try and find a workaround, I imagine. I'm not sure why we haven't come across this in the past.

**Comment by fixmystreetfr** [comment] 2015-10-21 20:00
Thank you for your investigation. I'll try to update the virtual env. But it will be well for others when use install script to get the virtual env in 2.7.4 directly. If you found a workaround i'm interested to know it.

**Comment by dracos** [comment] 2015-10-22 15:18
I don't really follow the second half of your comment, I'm afraid – if your terminal isn't capable of displaying UTF-8 characters correctly (could you try setting it to UTF-8) then you will be seeing all sorts of weird characters that will interfere with your terminal display.

The issue is definitely with the import script, as I've said; I have pushed a fix to that script that should hopefully allow this script to work in python 2.7 prior to 2.7.4, thanks for letting us know about it :)

**Closed** 2015-10-22 15:18 UTC
Labels: Reviewing

**Comment by fixmystreetfr** [comment] 2015-10-22 21:19
yes was my terminal from others computers not in UTF-8, but now i've got, any clues to correct it ?
(virtualenv-mapit)mapit@mapit:~/mapit$ ./manage.py migrate mapit
Operations to perform:
  Apply all migrations: mapit
Running migrations:
  Applying mapit.0001_initial... OK
  Applying mapit.0002_auto_20141218_1615... OK
(virtualenv-mapit)mapit@mapit:~/mapit$ ./manage.py loaddata global
Installed 23 object(s) from 1 fixture(s)
(virtualenv-mapit)mapit@mapit:~/mapit$ ./manage.py mapit_generation_create \
>     --commit --desc "Initial import of MapIt Global data"
Creating generation...
...saved: Generation 1 (inactive)
(virtualenv-mapit)mapit@mapit:~/mapit$ ./manage.py mapit_global_import --verbosity 2 --commit data/cache-with-political/
Loading any admin boundaries from data/cache-with-political/
Finding language codes...
Loading type O02
Loading all KML in O02
[0% complete] Loading /mnt/sdb1/data/cache-with-political/O02/relation-108089-Ecuador.kml
  Ecuador
    No area existed in the current generation with that OSM element type and ID
    Area ID: 1
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 503, in handle
    label_output = self.handle_label(label, **options)
  File "/var/www/mapit.fixmystreet.fr/mapit/mapit_global/management/commands/mapit_global_import.py", line 298, in handle_label
    m.names.update_or_create(type=name_type, defaults={'name': translated_name})
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 439, in update_or_create
    obj, created = self._create_object_from_params(lookup, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 465, in _create_object_from_params
    six.reraise(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 457, in _create_object_from_params
    obj.save(force_insert=True, using=self.db)
  File "/var/www/mapit.fixmystreet.fr/mapit/mapit/models.py", line 375, in save
    super(Name, self).save(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 590, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 618, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 699, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 732, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 920, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "area_id" violates not-null constraint

**Comment by fixmystreetfr** [comment] 2015-10-22 23:06
I solved this error with a simple upgrade of Django > 1.8" in the virtualenv.
For information I had updating python to 2.7.4 in the virtualenv like you told me. 
Django 1.7 with python2.7.4 failed on the mapit_global_import script with an area_id error.
From now import is working so when it'll finish i'll tell you more about the results.

**Comment by fixmystreetfr** [comment] 2015-10-23 01:44
it's work :)

./manage.py mapit_global_import --verbosity 2 --commit data/cache-with-political/
 [99% complete] Loading /var/www/mapit.fixmystreet.fr/mapit/data/cache-with-political/OWA/way-285853570-Wahlbezirk 9.kml
  Wahlbezirk 9
    No area existed in the current generation with that OSM element type and ID
    Area ID: 404476

./manage.py mapit_generation_activate --commit
Generation 1 (active) - activated

**Comment by dracos** [comment] 2015-10-23 09:56
Glad to hear you've got it running. I'm surprised at the IntegrityError though, it should work under 1.7 fine (that's what we currently run it under anyway!); could you provide the full traceback of that error too, so I can see where it came from?

**Comment by fixmystreetfr** [comment] 2015-10-23 10:20
(virtualenv-mapit)mapit@mapit:~/mapit$ ./manage.py migrate mapit
Operations to perform:
  Apply all migrations: mapit
Running migrations:
  Applying mapit.0001_initial... OK
  Applying mapit.0002_auto_20141218_1615... OK
(virtualenv-mapit)mapit@mapit:~/mapit$ ./manage.py loaddata global
Installed 23 object(s) from 1 fixture(s)
(virtualenv-mapit)mapit@mapit:~/mapit$ ./manage.py mapit_generation_create \
>     --commit --desc "Initial import of MapIt Global data"
Creating generation...
...saved: Generation 1 (inactive)
(virtualenv-mapit)mapit@mapit:~/mapit$ ./manage.py mapit_global_import --verbosity 2 --commit data/cache-with-political/
Loading any admin boundaries from data/cache-with-political/
Finding language codes...
Loading type O02
Loading all KML in O02
[0% complete] Loading data/cache-with-political/O02/relation-108089-Ecuador.kml
  Ecuador
    No area existed in the current generation with that OSM element type and ID
    Area ID: 1
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 503, in handle
    label_output = self.handle_label(label, **options)
  File "/var/www/mapit.test.fr/mapit/mapit_global/management/commands/mapit_global_import.py", line 298, in handle_label
    m.names.update_or_create(type=name_type, defaults={'name': translated_name})
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 439, in update_or_create
    obj, created = self._create_object_from_params(lookup, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 465, in _create_object_from_params
    six.reraise(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 457, in _create_object_from_params
    obj.save(force_insert=True, using=self.db)
  File "/var/www/mapit.test.fr/mapit/mapit/models.py", line 375, in save
    super(Name, self).save(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 590, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 618, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 699, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 732, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 920, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "area_id" violates not-null constraint

**Comment by dracos** [comment] 2015-10-23 10:46
That sounds like bug https://code.djangoproject.com/ticket/23611 which was present in Django 1.7 but fixed in 1.7.1. Sorry I wasn't clear about the version to use; in general, you should make sure you're using the last point release of a series e.g. in this instance 1.7.10. But if it also works in 1.8, that's good, I'd hoped it would :)
